name = "Spamventure"
description = """
Contributed as a programmer and pixel-artist in a platformer
"""
repo_url = "https://github.com/IWantMyLemons/Feed-The-Cat"
itch_url = "https://i-ate-a-lemon.itch.io/spamventure"