name = "Flare Discord Bot"
description = """
Rust-based discord bot with a custom self-made framework built
to allow bash-like command execution
"""
repo_url = "https://github.com/IWantMyLemons/flare-discord-bot"
